export const countries = [
  { value: "AF", label: "Afghanistan", flag: "af", dialCode: "+93" },
  { value: "AL", label: "Albania", flag: "al", dialCode: "+355" },
  { value: "DZ", label: "Algeria", flag: "dz", dialCode: "+213" },
  { value: "AD", label: "Andorra", flag: "ad", dialCode: "+376" },
  { value: "AO", label: "Angola", flag: "ao", dialCode: "+244" },
  { value: "AR", label: "Argentina", flag: "ar", dialCode: "+54" },
  { value: "AM", label: "Armenia", flag: "am", dialCode: "+374" },
  { value: "AU", label: "Australia", flag: "au", dialCode: "+61" },
  { value: "AT", label: "Austria", flag: "at", dialCode: "+43" },
  { value: "AZ", label: "Azerbaijan", flag: "az", dialCode: "+994" },
  { value: "BH", label: "Bahrain", flag: "bh", dialCode: "+973" },
  { value: "BD", label: "Bangladesh", flag: "bd", dialCode: "+880" },
  { value: "BY", label: "Belarus", flag: "by", dialCode: "+375" },
  { value: "BE", label: "Belgium", flag: "be", dialCode: "+32" },
  { value: "BZ", label: "Belize", flag: "bz", dialCode: "+501" },
  { value: "BJ", label: "Benin", flag: "bj", dialCode: "+229" },
  { value: "BT", label: "Bhutan", flag: "bt", dialCode: "+975" },
  { value: "BO", label: "Bolivia", flag: "bo", dialCode: "+591" },
  { value: "BR", label: "Brazil", flag: "br", dialCode: "+55" },
  { value: "BN", label: "Brunei", flag: "bn", dialCode: "+673" },
  { value: "BG", label: "Bulgaria", flag: "bg", dialCode: "+359" },
  { value: "CA", label: "Canada", flag: "ca", dialCode: "+1" },
  { value: "CN", label: "China", flag: "cn", dialCode: "+86" },
  { value: "CO", label: "Colombia", flag: "co", dialCode: "+57" },
  { value: "HR", label: "Croatia", flag: "hr", dialCode: "+385" },
  { value: "CU", label: "Cuba", flag: "cu", dialCode: "+53" },
  { value: "CZ", label: "Czech Republic", flag: "cz", dialCode: "+420" },
  { value: "DK", label: "Denmark", flag: "dk", dialCode: "+45" },
  { value: "EG", label: "Egypt", flag: "eg", dialCode: "+20" },
  { value: "FR", label: "France", flag: "fr", dialCode: "+33" },
  { value: "DE", label: "Germany", flag: "de", dialCode: "+49" },
  { value: "GR", label: "Greece", flag: "gr", dialCode: "+30" },
  { value: "HK", label: "Hong Kong", flag: "hk", dialCode: "+852" },
  { value: "IN", label: "India", flag: "in", dialCode: "+91" },
  { value: "ID", label: "Indonesia", flag: "id", dialCode: "+62" },
  { value: "IR", label: "Iran", flag: "ir", dialCode: "+98" },
  { value: "IQ", label: "Iraq", flag: "iq", dialCode: "+964" },
  { value: "IE", label: "Ireland", flag: "ie", dialCode: "+353" },
  { value: "IL", label: "Israel", flag: "il", dialCode: "+972" },
  { value: "IT", label: "Italy", flag: "it", dialCode: "+39" },
  { value: "JP", label: "Japan", flag: "jp", dialCode: "+81" },
  { value: "JO", label: "Jordan", flag: "jo", dialCode: "+962" },
  { value: "KZ", label: "Kazakhstan", flag: "kz", dialCode: "+7" },
  { value: "KE", label: "Kenya", flag: "ke", dialCode: "+254" },
  { value: "KW", label: "Kuwait", flag: "kw", dialCode: "+965" },
  { value: "MY", label: "Malaysia", flag: "my", dialCode: "+60" },
  { value: "MX", label: "Mexico", flag: "mx", dialCode: "+52" },
  { value: "MA", label: "Morocco", flag: "ma", dialCode: "+212" },
  { value: "NP", label: "Nepal", flag: "np", dialCode: "+977" },
  { value: "NL", label: "Netherlands", flag: "nl", dialCode: "+31" },
  { value: "NZ", label: "New Zealand", flag: "nz", dialCode: "+64" },
  { value: "NG", label: "Nigeria", flag: "ng", dialCode: "+234" },
  { value: "NO", label: "Norway", flag: "no", dialCode: "+47" },
  { value: "PK", label: "Pakistan", flag: "pk", dialCode: "+92" },
  { value: "PH", label: "Philippines", flag: "ph", dialCode: "+63" },
  { value: "PL", label: "Poland", flag: "pl", dialCode: "+48" },
  { value: "PT", label: "Portugal", flag: "pt", dialCode: "+351" },
  { value: "QA", label: "Qatar", flag: "qa", dialCode: "+974" },
  { value: "RU", label: "Russia", flag: "ru", dialCode: "+7" },
  { value: "SA", label: "Saudi Arabia", flag: "sa", dialCode: "+966" },
  { value: "SG", label: "Singapore", flag: "sg", dialCode: "+65" },
  { value: "ZA", label: "South Africa", flag: "za", dialCode: "+27" },
  { value: "KR", label: "South Korea", flag: "kr", dialCode: "+82" },
  { value: "ES", label: "Spain", flag: "es", dialCode: "+34" },
  { value: "LK", label: "Sri Lanka", flag: "lk", dialCode: "+94" },
  { value: "SE", label: "Sweden", flag: "se", dialCode: "+46" },
  { value: "CH", label: "Switzerland", flag: "ch", dialCode: "+41" },
  { value: "TH", label: "Thailand", flag: "th", dialCode: "+66" },
  { value: "TR", label: "Turkey", flag: "tr", dialCode: "+90" },
  { value: "UA", label: "Ukraine", flag: "ua", dialCode: "+380" },
  { value: "AE", label: "United Arab Emirates", flag: "ae", dialCode: "+971" },
  { value: "GB", label: "United Kingdom", flag: "gb", dialCode: "+44" },
  { value: "US", label: "United States", flag: "us", dialCode: "+1" },
  { value: "VN", label: "Vietnam", flag: "vn", dialCode: "+84" },
];
